version: '3.7'
services:
    medidor:
        image: alexjrjr/app-gauge
        tty: true
        stdin_open: true
        container_name: gauge-app	
        ports:
          - 8924:8923
        network_mode: bridge